In [1]:
import pandas as pd

In [2]:
data = [[1, 'War', 'great 3D', 8.9], [2, 'Science', 'fiction', 8.5], [3, 'irish', 'boring', 6.2], [4, 'Ice song', 'Fantacy', 8.6], [5, 'House card', 'Interesting', 9.1]]
cinema = pd.DataFrame(data, columns=['id', 'movie', 'description', 'rating']).astype({'id':'Int64', 'movie':'object', 'description':'object', 'rating':'Float64'})

In [3]:
cinema

   id       movie  description  rating
0   1         War     great 3D     8.9
1   2     Science      fiction     8.5
2   3       irish       boring     6.2
3   4    Ice song      Fantacy     8.6
4   5  House card  Interesting     9.1

In [6]:
cinema[(cinema['id'] % 2 != 0) & (cinema['description'] != 'boring')].sort_values(by= 'rating',ascending=False)

   id       movie  description  rating
4   5  House card  Interesting     9.1
0   1         War     great 3D     8.9

In [8]:
cinema.query('id % 2 != 0 and description != "boring"').sort_values(by='rating', ascending=False)

/var/folders/p3/g25fc4fn5_94qr376nhv0tk80000gn/T/ipykernel_2519/395306240.py:1: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  cinema.query('id % 2 != 0 and description != "boring"').sort_values(by='rating', ascending=False)

   id       movie  description  rating
4   5  House card  Interesting     9.1
0   1         War     great 3D     8.9