In [1]:
import pandas as pd

In [2]:
data = [[13, 15, 30], [10, 20, 15]]
triangle = pd.DataFrame(data, columns=['x', 'y', 'z']).astype({'x':'Int64', 'y':'Int64', 'z':'Int64'})

In [3]:
triangle

    x   y   z
0  13  15  30
1  10  20  15

In [20]:
triangle['triangle'] = 'No'

In [26]:
triangle.loc[(triangle['x']+triangle['y'] > triangle['z']) & (triangle['x']+triangle['z']>triangle['y']) & (triangle['y']+triangle['z']>triangle['x']), 'triangle'] = 'Yes'

In [27]:
triangle

    x   y   z triangle
0  13  15  30       No
1  10  20  15      Yes